### ISSUE TITLE
Could not locate the bindings file

### ISSUE THREAD

**Issue by iDevo** [FWeinb/homebridge-rcswitch#2]
Hi there!
I'm trying to run the rcswitch plugin on my RaspberryPi 2 but every time I'm starting homebridge I'm getting this error message while it is starting homebrige:

[Sun May 01 2016 21:13:10 GMT+0000 (UTC)] ====================
[Sun May 01 2016 21:13:10 GMT+0000 (UTC)] ERROR LOADING PLUGIN homebridge-rcswitch:
[Sun May 01 2016 21:13:10 GMT+0000 (UTC)] Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/build/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/build/Debug/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/build/Release/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/out/Debug/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/Debug/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/out/Release/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/Release/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/build/default/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/compiled/4.2.1/linux/arm/rcswitch.node
    at bindings (/usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/index.js:1:97)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rcswitch/index.js:1:78)
    at Module._compile (module.js:435:26)
[Sun May 01 2016 21:13:10 GMT+0000 (UTC)] ====================

I just followed the provided and very simple instructions but without success.
Is it possible, that I misconfigured something?

Thank you very much and best regards!

**UPDATE:**
I just installed homebridge-rcswitch-gpiomem and overwrite its index.js as well as package.json with your files and make some changes in the index.js to let homebridge think this is the gpiomem index.js and it worked.
Never the less is it possible to make a fix?

**Comment by zvaehn** [comment]
I got the same error
