### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-rcswitch

### ISSUE THREAD

**Issue by heydemar** [FWeinb/homebridge-rcswitch#4]
Hi, 

i have the Problem if i start the homebridge:
[2016-09-26 16:07:45] ERROR LOADING PLUGIN homebridge-rcswitch:
[2016-09-26 16:07:45] Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/build/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/build/Debug/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/build/Release/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/out/Debug/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/Debug/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/out/Release/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/Release/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/build/default/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/compiled/4.0.0/linux/arm/rcswitch.node
    at bindings (/usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/index.js:1:97)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rcswitch/index.js:1:78)
    at Module._compile (module.js:434:26)
[2016-09-26 16:07:45] ====================

Can someone help me? 

Thanks

**Comment by fynnit** [comment]
have the same one! 

ERROR LOADING PLUGIN homebridge-rcswitch:
[10/31/2016, 10:22:19 PM] Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/build/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/build/Debug/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/build/Release/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/out/Debug/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/Debug/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/out/Release/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/Release/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/build/default/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/compiled/4.0.0/linux/arm/rcswitch.node
    at bindings (/usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/index.js:1:97)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rcswitch/index.js:1:78)
    at Module._compile (module.js:434:26)

**Comment by fynnit** [comment]
even with a newer node version its not working.

can you fix this @FWeinb ?

`[11/1/2016, 6:52:47 PM] ====================
[11/1/2016, 6:52:47 PM] ERROR LOADING PLUGIN homebridge-rcswitch:
[11/1/2016, 6:52:47 PM] Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/build/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/build/Debug/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/build/Release/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/out/Debug/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/Debug/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/out/Release/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/Release/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/build/default/rcswitch.node
 → /usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/compiled/6.9.1/linux/arm/rcswitch.node
    at bindings (/usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rcswitch/node_modules/rcswitch/index.js:1:97)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-rcswitch/index.js:1:78)
[11/1/2016, 6:52:47 PM] ====================`

**Comment by zvaehn** [comment]
same :(
